name: createunion
description: 强创联合

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  shared_preferences: ^0.5.7
  common_utils: ^1.2.1
  permission_handler: ^5.0.1+1
  path_provider: ^1.6.18
  fbroadcast: ^1.0.2
  fsuper: ^2.0.2
  fdottedline: ^1.0.1
  fradio: ^1.0.1
  screen: ^0.0.5
  flustars: ^0.3.3
  open_file: ^3.0.1
  url_launcher: ^5.7.2
  bot_toast: ^3.0.4
  package_info: ^0.4.3
  connectivity: ^0.4.9
  flutter_sound_lite: ^6.2.0
  flutter_slidable: ^0.5.7
  extended_image: ^1.2.0
  wrapper: ^1.0.1
  flutter_swiper: ^1.1.6
  flutter_svg: ^0.19.0
  image_picker: ^0.6.7

  image_pickers:
    git:
      url: https://devops.rubikstack.com:10080/surface/image_pickers.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/